const Constants = {
    CHANGE_PICTURE: 'CHANGE_PICTURE',
    ADD_NEW_PICTURE: 'ADD_NEW_PICTURE',
    DELETE_PICTURE: 'DELETE_PICTURE',
    TOGGLE_EDITABLE: 'TOGGLE_EDITABLE',
    CHANGE_TOOLTIP: 'CHANGE_TOOLTIP',
};

export default Constants;